// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCyKXom7QhHn3RXWALT2aiChutqdQ2Ivc',
    appId: '1:852678664455:web:4999e1c3a03ccd3be3a5a2',
    messagingSenderId: '852678664455',
    projectId: 'clothex-app',
    authDomain: 'clothex-app.firebaseapp.com',
    storageBucket: 'clothex-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh3eqIIG7kGdtsnF7jjO6fLPlK0M_IvKg',
    appId: '1:852678664455:android:79d2b6a20dbb6f78e3a5a2',
    messagingSenderId: '852678664455',
    projectId: 'clothex-app',
    storageBucket: 'clothex-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA98OpoftTmEZRbZJnFWfIxzv2CkJrPBVY',
    appId: '1:852678664455:ios:fd61287a0ecedaeae3a5a2',
    messagingSenderId: '852678664455',
    projectId: 'clothex-app',
    storageBucket: 'clothex-app.appspot.com',
    iosBundleId: 'com.example.clothexApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA98OpoftTmEZRbZJnFWfIxzv2CkJrPBVY',
    appId: '1:852678664455:ios:74f7898de8b5f0cbe3a5a2',
    messagingSenderId: '852678664455',
    projectId: 'clothex-app',
    storageBucket: 'clothex-app.appspot.com',
    iosBundleId: 'com.example.clothexApp.RunnerTests',
  );
}
